### ISSUE TITLE
[Feature Request] Add possiblity to filter out lines based on keyword

### ISSUE THREAD

**Issue by EssKayz** [snakefoot/snaketail-net#115] opened 2018-06-01 09:36 UTC
It would be great if it was possible to filter out crud lines from server logs, like only leaving errors and critical errors and skipping information fields out, so that you could at a quick glance see if there's been any errors lately (especially with a logfile that scrolls 100s of lines per second)

**Comment by treflip** [comment] 2018-10-03 19:01
Me too. This would be great for quickly finding errors or timed events. I currently use Notepad++ analyzer plug in for this which works well but am liking snake tail a lot and could eliminate the other tool with a filter ability!

**Comment by snakefoot** [comment] 2023-04-27 17:02
Closed as duplicate of #20

**Closed by snakefoot** 2023-04-27 17:02 UTC
