### ISSUE TITLE
Log being cut off?

### ISSUE THREAD

**Issue by chobo2** [snakefoot/snaketail-net#98] opened 2016-04-14 16:09 UTC
Hi

I noticed when I open a log in snaketail and the line is too long it just cut off valuable logging information.

When I open it in notepad, I see all the information.

How do I make it so I see everything and not cutoff information?

**Comment by snakefoot** [comment] 2016-08-17 19:50
Duplicate of #32

**Closed by snakefoot** 2016-08-17 19:50 UTC
Labels: bug, duplicate
