### ISSUE TITLE
SnakeTail hanging

### ISSUE THREAD

**Issue by GoogleCodeExporter** [snakefoot/snaketail-net#55] opened 2015-03-17 21:48 UTC
```
What steps will reproduce the problem?
1. Run for several minutes
2. Snaketail hangs
3. Resource monitor shows wait chain svchost -k LocalServiceNetworkRestricted

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?
1.8.2.0

Please provide any additional information below.
Running behind corporate firewall 

```

Original issue reported on code.google.com by `spu...@gmail.com` on 3 Sep 2013 at 7:57

**Comment by snakefoot** [comment] 2015-08-18 19:03
Will close this issue because of age and lack of information (No minidump or steps to reproduce).

**Closed** 2015-08-18 19:04 UTC
Labels: bug
