### ISSUE TITLE
Feature Request 🔎 Highlight lines

### ISSUE THREAD

**Issue by stilicrafter** [snakefoot/snaketail-net#159] opened 2023-04-26 16:42 UTC
Hi,
i would love to see a feature to color lines by contenct.
Ex: 
![image](https://user-images.githubusercontent.com/22886797/234643574-c67656f0-4621-4808-bd78-5090c760241a.png)
--> Querry: thread1
![image](https://user-images.githubusercontent.com/22886797/234644652-6c2bcb77-4303-4067-aa81-f30ba14eb29d.png)
or highlight the whole line 

![image](https://user-images.githubusercontent.com/22886797/234645121-98bd86f0-7b4e-47fd-b5ee-9d9dd4830f3a.png)

or by word
![image](https://user-images.githubusercontent.com/22886797/234644862-60ec5b22-04f4-4292-957d-d99d71dde29e.png)

**Comment by snakefoot** [comment] 2023-04-26 18:30
Line-higlighting already exists, except the word-specific-highlighting

![image](https://user-images.githubusercontent.com/11509660/234669580-58cffa05-a8a9-4dad-98f4-2aad432593e3.png)

Just add "keywords" that should trigger line-highlight.

**Comment by snakefoot** [comment] 2023-04-27 16:57
Closing as duplicate of #12

**Closed by snakefoot** 2023-04-27 16:57 UTC

**Comment by stilicrafter** [comment] 2023-04-27 17:08
Didnt know it was unter view. Thanks for your assistance. 👍
