### ISSUE TITLE
Mark text in a line

### ISSUE THREAD

**Issue by ghuacc** [snakefoot/snaketail-net#96] opened 2016-03-22 14:24 UTC
Marking e.g. an IP address or a word in a line does not work like in most other editors.
I'd propose a **double-click** to mark a **word** between space signs, and a **triple-click** for a **whole line**, similar to Notepad++.

**Comment by ferpega** [comment] 2017-08-18 12:09
I would like to be able to select/copy text from the line and not the whole line.

**Comment by UselessGuru** [comment] 2018-07-04 16:42
Second this. This is something I really miss in this very useful program. 👍

**Comment by snakefoot** [comment] 2023-04-27 16:59
Closing as duplicate of #60

**Closed by snakefoot** 2023-04-27 16:59 UTC
