### ISSUE TITLE
Log Filtering

### ISSUE THREAD

**Issue by NetSolutionArchitect** [snakefoot/snaketail-net#132] opened 2019-06-17 17:07 UTC
It would be nice to have log filtering, based on phrase criteria/regex. After applying the filter, only corresponding data would be visible on screen.

Multi-filters would be even more convenient to have :)

**Comment by snakefoot** [comment] 2023-04-27 17:00
Close as duplicate of #115

**Closed by snakefoot** 2023-04-27 17:00 UTC
Labels: enhancement
